//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Bysxiang.UipathExcelEx.Resources {
    using System;
    
    
    /// <summary>
    ///   一个强类型的资源类，用于查找本地化的字符串等。
    /// </summary>
    // 此类是由 StronglyTypedResourceBuilder
    // 类通过类似于 ResGen 或 Visual Studio 的工具自动生成的。
    // 若要添加或移除成员，请编辑 .ResX 文件，然后重新运行 ResGen
    // (以 /str 作为命令选项)，或重新生成 VS 项目。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   返回此类使用的缓存的 ResourceManager 实例。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Bysxiang.UipathExcelEx.Resources.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   重写当前线程的 CurrentUICulture 属性，对
        ///   使用此强类型资源类的所有资源查找执行重写。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   查找类似 MatchFunc 的本地化字符串。
        /// </summary>
        internal static string ExcelFindValue_MatchFunc {
            get {
                return ResourceManager.GetString("ExcelFindValue_MatchFunc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 ExcelFindValue 的本地化字符串。
        /// </summary>
        internal static string ExcelFindValue_Name {
            get {
                return ResourceManager.GetString("ExcelFindValue_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 SearchValue 的本地化字符串。
        /// </summary>
        internal static string ExcelFindValue_Search {
            get {
                return ResourceManager.GetString("ExcelFindValue_Search", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 WhichNum 的本地化字符串。
        /// </summary>
        internal static string ExcelFindValue_WhichNum {
            get {
                return ResourceManager.GetString("ExcelFindValue_WhichNum", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Excel Range 的本地化字符串。
        /// </summary>
        internal static string ExcelRange {
            get {
                return ResourceManager.GetString("ExcelRange", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Excel Range Cannot be Empty. 的本地化字符串。
        /// </summary>
        internal static string ExcelRangeEmptyException {
            get {
                return ResourceManager.GetString("ExcelRangeEmptyException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Sheet: {0}, Ragne: {1} Invalid. 的本地化字符串。
        /// </summary>
        internal static string ExcelRangeException {
            get {
                return ResourceManager.GetString("ExcelRangeException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 ExcelReadRange 的本地化字符串。
        /// </summary>
        internal static string ExcelReadRange_Name {
            get {
                return ResourceManager.GetString("ExcelReadRange_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Search Value 的本地化字符串。
        /// </summary>
        internal static string ExcelSearch {
            get {
                return ResourceManager.GetString("ExcelSearch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 ExcelUsedRange 的本地化字符串。
        /// </summary>
        internal static string ExcelUsedRange_Name {
            get {
                return ResourceManager.GetString("ExcelUsedRange_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 The UsedRange cannot be obtained 的本地化字符串。
        /// </summary>
        internal static string ExcelUsedRangeException {
            get {
                return ResourceManager.GetString("ExcelUsedRangeException", resourceCulture);
            }
        }
    }
}
